/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.material;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.database.Material;
import model.database.Personal;

/**
 *
 * @author neira
 */
public class MaterialDialog extends javax.swing.JDialog {

    /**
     * Creates new form MaterialDialog
     */
    public MaterialDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaterial = new javax.swing.JTable();
        btnAddArticulo = new javax.swing.JButton();
        btnEliminarArticulo = new javax.swing.JButton();
        btnVolverMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 53, 96));
        jPanel1.setPreferredSize(new java.awt.Dimension(811, 370));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Material");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 312));

        tablaMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMaterial);

        btnAddArticulo.setBackground(new java.awt.Color(251, 234, 136));
        btnAddArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/plus-5-32.png"))); // NOI18N
        btnAddArticulo.setText("Añadir articulo");
        btnAddArticulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddArticulo.setMaximumSize(new java.awt.Dimension(162, 39));
        btnAddArticulo.setMinimumSize(new java.awt.Dimension(162, 39));
        btnAddArticulo.setName(""); // NOI18N
        btnAddArticulo.setPreferredSize(new java.awt.Dimension(162, 39));

        btnEliminarArticulo.setBackground(new java.awt.Color(251, 234, 136));
        btnEliminarArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/x-mark-4-32.png"))); // NOI18N
        btnEliminarArticulo.setText("Eliminar articulo");
        btnEliminarArticulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminarArticulo.setMaximumSize(new java.awt.Dimension(162, 39));
        btnEliminarArticulo.setMinimumSize(new java.awt.Dimension(162, 39));
        btnEliminarArticulo.setName(""); // NOI18N
        btnEliminarArticulo.setPreferredSize(new java.awt.Dimension(162, 39));

        btnVolverMaterial.setBackground(new java.awt.Color(251, 234, 136));
        btnVolverMaterial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/volver32.png"))); // NOI18N
        btnVolverMaterial.setText("Volver");
        btnVolverMaterial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolverMaterial.setMaximumSize(new java.awt.Dimension(162, 39));
        btnVolverMaterial.setMinimumSize(new java.awt.Dimension(162, 39));
        btnVolverMaterial.setName(""); // NOI18N
        btnVolverMaterial.setPreferredSize(new java.awt.Dimension(162, 39));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(btnEliminarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVolverMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolverMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param listener
     */
    public void setAddArticuloActionListener(ActionListener listener){
        this.btnAddArticulo.addActionListener(listener);
    }
    
    public void setEliminarArticuloActionListener(ActionListener listener){
        this.btnEliminarArticulo.addActionListener(listener);
    }
    
    public void setVolverMaterialActionListener(ActionListener listener){
        this.btnVolverMaterial.addActionListener(listener);
    }
   
    public JTable getMaterialTabla(){
        return tablaMaterial;
    }
    
    public void mostrarMaterial(ArrayList<Material> articulos) {
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaMaterial.getModel();
       
        modeloTabla.setRowCount(0);

        for (Material material : articulos) {
            Object[] fila = {material.getIdArticulo(),material.getNombreArticulo(),material.getUnidadesDisponibles(),material.getUnidadesNoDisponibles()};
            modeloTabla.addRow(fila);
        }

        tablaMaterial.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArticulo;
    private javax.swing.JButton btnEliminarArticulo;
    private javax.swing.JButton btnVolverMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMaterial;
    // End of variables declaration//GEN-END:variables
}
