/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.eventos;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 *
 * @author neira
 */
public class AddEventoDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddEventoDialog
     */
    public AddEventoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoEventoButtonGroup = new javax.swing.ButtonGroup();
        fotomatonButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipoEventoBodaRadioButton = new javax.swing.JRadioButton();
        tipoEventoFiestaRadioButton = new javax.swing.JRadioButton();
        packsBodaComboBox = new javax.swing.JComboBox<>();
        packsFiestaComboBox = new javax.swing.JComboBox<>();
        siFotomatonRadioButton = new javax.swing.JRadioButton();
        noFotomatonRadioButton = new javax.swing.JRadioButton();
        horasExtraFotomatonSpinner = new javax.swing.JSpinner();
        horasExtraDiscoSpinner = new javax.swing.JSpinner();
        btnCrearEvento = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        clientesComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        empleado1ComboBox = new javax.swing.JComboBox<>();
        empleado2ComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        furgonetaComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 53, 96));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Creador de eventos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fotomatón: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Packs Boda: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de evento: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Horas extra Fotomatón:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Horas extra Disco:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Packs Fiesta:");

        tipoEventoBodaRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoEventoBodaRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tipoEventoBodaRadioButton.setText("Boda");

        tipoEventoFiestaRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoEventoFiestaRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tipoEventoFiestaRadioButton.setText("Fiesta");
        tipoEventoFiestaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEventoFiestaRadioButtonActionPerformed(evt);
            }
        });

        packsBodaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base", "Pro", "Diamante", "Platino" }));

        packsFiestaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disco Móvil", "Karaoke", "Proyección" }));

        siFotomatonRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        siFotomatonRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        siFotomatonRadioButton.setText("Si");

        noFotomatonRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        noFotomatonRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        noFotomatonRadioButton.setText("No");

        horasExtraFotomatonSpinner.setModel(new javax.swing.SpinnerNumberModel(0, null, 5, 1));

        horasExtraDiscoSpinner.setModel(new javax.swing.SpinnerNumberModel(0, null, 5, 1));

        btnCrearEvento.setText("Crear");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cliente:");

        clientesComboBox.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Empleados:");

        empleado1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No" }));

        empleado2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Vehículo:");

        furgonetaComboBox.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(clientesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(tipoEventoBodaRadioButton)
                                                    .addGap(18, 18, 18))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(siFotomatonRadioButton)
                                                    .addGap(44, 44, 44)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(noFotomatonRadioButton)
                                                .addComponent(tipoEventoFiestaRadioButton)
                                                .addComponent(horasExtraFotomatonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(65, 65, 65))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(packsBodaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(181, 181, 181)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(199, 199, 199)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(empleado1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(empleado2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(packsFiestaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(furgonetaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horasExtraDiscoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(btnCrearEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(clientesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(empleado1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoEventoBodaRadioButton)
                    .addComponent(tipoEventoFiestaRadioButton)
                    .addComponent(jLabel10)
                    .addComponent(furgonetaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(packsBodaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(packsFiestaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(siFotomatonRadioButton)
                    .addComponent(noFotomatonRadioButton)
                    .addComponent(jLabel6)
                    .addComponent(horasExtraDiscoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(horasExtraFotomatonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnCrearEvento)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoEventoFiestaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEventoFiestaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoEventoFiestaRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setAñadirClienteActionListener(ActionListener listener){
        btnCrearEvento.addActionListener(listener);
    }
    
    public JComboBox getComboBoxClientes(){
        return clientesComboBox;
    }
    
    public JComboBox getComboBoxEmpleado1(){
        return empleado1ComboBox;
    }
        
    public JComboBox getComboBoxEmpleado2(){
        return empleado2ComboBox;
    }   
    
    public JComboBox getComboBoxFurgoneta(){
        return furgonetaComboBox;
    }   
    
    public JComboBox getComboBoxPacksBoda(){
        return packsBodaComboBox;
    } 
    
    public JComboBox getComboBoxPacksFiesta(){
        return packsFiestaComboBox;
    } 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearEvento;
    private javax.swing.JComboBox<String> clientesComboBox;
    private javax.swing.JComboBox<String> empleado1ComboBox;
    private javax.swing.JComboBox<String> empleado2ComboBox;
    private javax.swing.ButtonGroup fotomatonButtonGroup;
    private javax.swing.JComboBox<String> furgonetaComboBox;
    private javax.swing.JSpinner horasExtraDiscoSpinner;
    private javax.swing.JSpinner horasExtraFotomatonSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton noFotomatonRadioButton;
    private javax.swing.JComboBox<String> packsBodaComboBox;
    private javax.swing.JComboBox<String> packsFiestaComboBox;
    private javax.swing.JRadioButton siFotomatonRadioButton;
    private javax.swing.JRadioButton tipoEventoBodaRadioButton;
    private javax.swing.ButtonGroup tipoEventoButtonGroup;
    private javax.swing.JRadioButton tipoEventoFiestaRadioButton;
    // End of variables declaration//GEN-END:variables
}
